#' Function to extract all output data from SWAT model output.rch, output.sub and output.hru files
#'
#'This function allows reading in all output.rch, output.sub, output.hru files generated by SWAT2012
#'in Lithuanian EPA model, which was applied for different climate and measures scenarios.
#'
#' @param watersheds_folder_path String giving path to the Watersheds folder where all output results are saved.
#' (example "../../MODEL/MODEL_CLIMATE_LONG/Setup/Watersheds")
#' @param climate_scenarios Vector providing climate data name used in saving modeling results.
#' For example, if results were saved in 'HIRHAM5_rcp45_measure_30'  and 'HIRHAM5_rcp85_measure_30'
#' when climate_scenarios = c("HIRHAM5_rcp45", "HIRHAM5_rcp85")
#' @param measure_scenarios Vector providing measures name used in saving modeling results.
#' For example, if results were saved in 'HIRHAM5_rcp45_measure_30'  and 'HIRHAM5_rcp45_measure_31'
#' when measure_scenarios = c("measure_30", "measure_31")
#' @param output_type Number the same as in IPRINT (0 - Monthly, 1 - Daily, 2 - Year)
#' @param starting_date Sting with time series starting date (example "1997-01-01")
#' @param ending_date Sting with time series ending date (example "2019-12-31")
#' @param save_results_to_files Logical value with TRUE or FALSE values. If TRUE  results will be saved to hru.rda,
#' rch.rda, sub.rda files in working directory.
#' @return List with three data.frames: rch, sub and hru for data extracted from different output files.
#' @importFrom sf st_set_geometry
#' @importFrom dplyr bind_cols bind_rows arrange %>%
#' @export
#' @example
#' r <- extract_watersheds_output("/Ws", c("C1", "C2"), c("M1", "M2"), 2, "1997-01-01", "2099-12-31")

extract_watersheds_output <- function(watersheds_folder_path, climate_scenarios, measure_scenarios,
                                      output_type, starting_date, ending_date, save_results_to_files = FALSE){

  #################################################################
  ####              Loop to extract modeling data              ####
  #################################################################
  ##Setting up dataframes
  df_rch <- NA
  df_sub <- NA
  df_hru <- NA
  ##Creating dataframe for looping over setups in modeling results
  setups_to_loop <- basins %>%
    st_set_geometry(NULL) %>%
    select(Subbasin, Setup_name) %>%
    unique() %>%
    arrange(Subbasin, Setup_name)
  ##Main loop to extract and save all modeling data
  for (row in 1:nrow(setups_to_loop)) {
    subbasin_name <- setups_to_loop[row, "Subbasin"]
    setup_name  <- setups_to_loop[row, "Setup_name"]
    print(paste("Started extracting", subbasin_name, setup_name))
    for (climate in climate_scenarios){
      for (measure in measure_scenarios){
        ##Forming path to modeling result folder
        scenario_path <- paste0(watersheds_folder_path, "/", subbasin_name,
                                "/", setup_name, "/SWAT/", climate, "_", measure)
        rch_path <- paste0(scenario_path, "/output.rch")
        sub_path <- paste0(scenario_path, "/output.sub")
        hru_path <- paste0(scenario_path, "/output.hru")

        ##Checking if files exists and they are not empty
        if (file.exists(rch_path) &
            file.info(rch_path) > 2000 &
            file.exists(sub_path) &
            file.info(sub_path) > 2000 &
            file.exists(hru_path) &
            file.info(hru_path) > 2000){
          ##Extracting and cleaning data from SWAT output.*** files
          ##Saving output.rch file
          rch <- clean_swat_output(read_swat_output(scenario_path, output_type,"rch",
                                                    starting_date, ending_date))
          rch <- bind_cols(rch, SUBBASIN = subbasin_name, SETUP = setup_name,
                           CLIMATE = climate, MEASURE = measure)
          ##Saving output.sub file
          sub <- clean_swat_output(read_swat_output(scenario_path, output_type,"sub",
                                                    starting_date, ending_date))
          sub <- bind_cols(sub, SUBBASIN = subbasin_name, SETUP = setup_name,
                           CLIMATE = climate, MEASURE = measure)
          ##Saving output.hru file
          hru <- clean_swat_output(read_swat_output(scenario_path, output_type,"hru",
                                                    starting_date, ending_date))
          hru <- bind_cols(hru, SUBBASIN = subbasin_name, SETUP = setup_name,
                           CLIMATE = climate, MEASURE = measure)

          ##Saving to a single dataframe each of output files.
          ##Add column for the scenario, which shows basins, setup, climate data and
          ##measure used.
          rch <- within(rch,  SCENARIO <- paste(SUBBASIN, SETUP, CLIMATE, MEASURE,
                                                sep="_"))
          sub <- within(sub,  SCENARIO <- paste(SUBBASIN, SETUP, CLIMATE, MEASURE,
                                                sep="_"))
          hru <- within(hru,  SCENARIO <- paste(SUBBASIN, SETUP, CLIMATE, MEASURE,
                                                sep="_"))

          ##Saving results
          if (row == 1){
            df_rch <- rch
            df_sub <- sub
            df_hru <- hru
          } else {
            df_rch <- bind_rows(df_rch, rch)
            df_sub <- bind_rows(df_sub, sub)
            df_hru <- bind_rows(df_hru, hru)
          }
        } else {
          message(paste0("OUTPUT files are missing for .rch, .sub or/and .hru in
                       path or files are empty", scenario_path, " !!!"))
        }
      }
    }
    print(paste("Finished extracting", subbasin_name, setup_name, ".",
                round(row/nrow(setups_to_loop)*100, 1), "% already done."))
  }

  ##Saving data to *.rda files
  if (save_results_to_files == TRUE){
    ##Saving results to files
    print("Results are being saved into .rda files.")
    save(df_rch, file = "rch.rda")
    save(df_sub, file = "sub.rda")
    save(df_hru, file = "hru.rda")
    print("Finished saving results into .rda files. rch.rda, sub.rda and hru.rda files are in working directory.")
  }

  print ("Extracting from Watersheds folder is finished!!!")

  ##Returning list with 3 dataframes.
  return(list(rch = df_rch, sub = df_sub, hru = df_hru))
}
